In [1]:
import pandas as pd

In [3]:
df_buurt = pd.read_csv('data/buurt_data.csv')

In [5]:
df_address = pd.read_csv('data/hackaton.csv')

In [6]:
df_address

,date,amount,build_year,build_type,use_surface,parcel_surface,lon,lat,energy_label,number_of_objects,buurt_code,id
0,31/10/2019,240000,1984,Flatwoning (overig),41,3004,4.880518,52.389801,B,15,3631301,0
1,31/10/2019,575000,1870,Flatwoning (overig),45,616,4.888572,52.377720,G,12,3630200,1
2,31/10/2019,358000,1940,Flatwoning (overig),40,124,4.881288,52.376377,D,8,3630611,2
3,31/10/2019,2800000,1770,Flatwoning (overig),196,146,4.886696,52.372057,G,3,3630202,3
4,31/10/2019,1017500,1910,Maisonnette,115,85,4.882979,52.368475,F,3,3630203,4
5,31/10/2019,2075000,2019,Flatwoning (overig),160,436,4.887275,52.364098,A,6,3630300,5
6,31/10/2019,765000,2003,Flatwoning (overig),90,100,4.893679,52.359622,B,5,3630705,6
7,31/10/2019,520000,2001,Flatwoning (overig),100,1137,4.912382,52.362260,B,38,3630801,7
8,31/10/2019,639000,1900,Maisonnette,64,108,4.919689,52.369686,C,2,3630902,8
9,31/10/2019,520000,1997,Flatwoning (overig),99,1792,4.938037,52.370260,C,59,3633306,9
10,31/10/2019,451000,1994,Flatwoning (overig),85,7719,4.947305,52.377413,B,225,3633303,10
11,31/10/2019,371000,2010,Flatwoning (overig),83,1143,4.931085,52.405178,A,33,3637402,11
12,31/10/2019,300000,1918,Rijwoning hoek,37,5118,4.927524,52.387234,G,1,3636102,12
13,31/10/2019,372500,1967,Flatwoning (overig),95,1429,4.949346,52.396726,G,65,3636801,13
14,31/10/2019,255000,1968,Flatwoning (overig),85,3291,4.957850,52.390952,C,96,3636805,14
15,31/10/2019,230123,1966,Flatwoning (overig),49,5389,4.946713,52.395638,C,8,3636802,15
16,31/10/2019,260000,1966,Flatwoning (overig),79,1048,4.947646,52.402266,E,56,3636912,16
17,31/10/2019,13191,2017,Flatwoning (overig),85,157,4.892229,52.401516,A,262,3637105,17
18,31/10/2019,590000,2007,Rijwoning tussen,166,126,4.901779,52.408216,A,1,3636503,18
19,31/10/2019,285550,1902,Flatwoning (overig),43,84,4.874118,52.383060,D,4,3631403,19
20,31/10/2019,315000,1916,Flatwoning (overig),42,95,4.869095,52.381780,E,4,3631404,20
21,31/10/2019,480000,1916,Flatwoning (overig),20,89,4.868317,52.381749,G,5,3631404,21
22,31/10/2019,393000,1904,Flatwoning (overig),40,78,4.860634,52.360846,C,5,3632100,22
23,31/10/2019,842000,1906,Flatwoning (overig),118,142,4.858980,52.360434,E,4,3632100,23
24,31/10/2019,396000,2008,Flatwoning (overig),72,4565,4.847349,52.376470,A,124,3633802,24
25,31/10/2019,397011,1940,Flatwoning (overig),64,142,4.850782,52.376764,G,4,3633802,25
26,31/10/2019,371001,1940,Flatwoning (overig),58,1423,4.852086,52.376985,D,4,3633802,26
27,31/10/2019,340000,1926,Flatwoning (overig),64,194,4.848599,52.383585,D,8,3633702,27
28,31/10/2019,620000,1924,Flatwoning (overig),49,160,4.859442,52.375859,B,4,3633703,28
29,31/10/2019,321000,1935,Flatwoning (overig),45,2212,4.863870,52.372760,D,8,3634000,29
...,...,...,...,...,...,...,...,...,...,...,...,...
4530776,2/1/1995,233697,1959,Flatwoning (overig),178,285,6.097628,53.107577,E,3,900001,4530776
4530777,2/1/1995,40840,1969,Flatwoning (overig),48,2253,6.427235,53.127352,E,71,16990000,4530777
4530778,2/1/1995,88033,1985,2-onder-1-kapwoning,126,268,6.408511,53.134145,C,1,16990010,4530778
4530779,2/1/1995,97563,1945,Vrijstaande woning,132,545,6.395826,53.130982,G,1,16990030,4530779
4530780,2/1/1995,27227,1940,Vrijstaande woning,180,408,6.456579,53.068034,G,1,16990300,4530780
4530781,2/1/1995,76689,1993,2-onder-1-kapwoning,106,224,6.344996,53.126089,B,1,19690500,4530781
4530782,2/1/1995,122521,1935,Vrijstaande woning,191,480,6.566004,52.989485,F,1,1060011,4530782
4530783,2/1/1995,201932,1988,Vrijstaande woning,188,503,6.576127,53.020947,B,1,1060705,4530783
4530784,2/1/1995,85311,1985,2-onder-1-kapwoning,131,217,6.566574,53.020979,C,1,1060602,4530784
4530785,2/1/1995,138403,1986,Vrijstaande woning,178,438,6.718864,53.054034,C,1,16800000,4530785
4530786,2/1/1995,128193,1991,Vrijstaande woning,153,1570,7.060194,52.862637,B,1,19500900,4530786
4530787,2/1/1995,33580,1901,2-onder-1-kapwoning,111,327,6.877963,53.100407,G,1,470003,4530787
4530788,2/1/1995,52185,1968,Rijwoning tussen,69,139,6.859012,53.105176,C,1,470005,4530788
4530789,2/1/1995,60353,1920,Vrijstaande woning,108,850,6.837809,53.055096,G,1,16801200,4530789
4530790,2/1/1995,77143,1903,Flatwoning (overig),35,100,6.573963,53.216589,G,2,140001,4530790
4530791,2/1/1995,158823,1987,NaN,158,117,6.574124,53.218291,NaN,1,140002,4530791
4530792,2/1/1995,158823,1915,Maisonnette,30,127,6.562445,53.224835,A,5,140005,4530792
4530793,2/1/1995,149747,1978,Rijwoning tussen,154,225,6.570960,53.188059,C,1,140606,4530793
4530794,2/1/1995,58991,1890,Rijwoning tussen,83,75,6.581082,53.201008,D,1,140604,4530794
4530795,2/1/1995,26092,1915,Rijwoning tussen,94,82,6.579448,53.213515,F,1,140101,4530795
4530796,2/1/1995,49916,1939,Flatwoning (overig),97,197,6.563156,53.206236,G,3,140103,4530796
4530797,2/1/1995,816804,2004,NaN,80,1751,6.587624,53.246634,NaN,4,141100,4530797
4530798,2/1/1995,62395,1927,2-onder-1-kapwoning,128,130,6.502069,53.212909,G,1,140800,4530798
4530799,2/1/1995,55588,1965,Vrijstaande woning,102,292,6.594629,53.300887,D,1,19660000,4530799
4530800,2/1/1995,56723,1994,Vrijstaande woning,135,954,6.279209,53.215900,A,1,19690000,4530800
4530801,2/1/1995,86218,1963,Vrijstaande woning,152,2500,6.253264,53.201677,B,1,19690001,4530801
4530802,2/1/1995,68067,2003,2-onder-1-kapwoning,155,242,6.856641,53.324052,B,1,30000,4530802
4530803,2/1/1995,34034,1976,2-onder-1-kapwoning,151,476,6.934623,53.250676,C,1,100944,4530803
4530804,2/1/1995,80546,1990,Vrijstaande woning,96,299,6.377216,53.356804,B,1,19661001,4530804
4530805,2/1/1995,31197,1928,Vrijstaande woning,110,242,6.636191,53.347510,G,1,240200,4530805

In [11]:
df_address.dtypes

date                  object
amount                 int64
build_year             int64
build_type            object
use_surface            int64
parcel_surface         int64
lon                  float64
lat                  float64
energy_label          object
number_of_objects      int64
buurt_code             int64
id                     int64
dtype: object

In [12]:
def amount_classes(amount):
    if amount < 100_000:
        return '50_000-100_000'
    elif amount < 150_000:
        return '100_000-150_000'
    elif amount < 200_000:
        return '150_000-200_000'
    elif amount < 250_000:
        return '200_000-250_000'
    elif amount < 300_000:
        return '250_000-300_000'
    elif amount < 350_000:
        return '300_000-350_000'
    elif amount < 400_000:
        return '350_000-400_000'
    elif amount < 500_000:
        return '400_000-500_000'
    elif amount < 750_000:
        return '500_000-750_000'
    elif amount < 1_000_000:
        return '750_000-1_000_000'
    elif amount < 1_500_000:
        return '1_000_000-1_500_000'
    elif amount <= 5_000_000:
        return '1_500_000-5_000_000'

In [16]:
def build_year_classes(year):
    if year < 1850:
        return '1050-1850'
    elif year < 1905:
        return '1850-1905'
    elif year < 1925:
        return '1905-1925'
    elif year < 1945:
        return '1925-1945'
    elif year < 1955:
        return '1945-1955'
    elif year < 1965:
        return '1955-1965'
    elif year < 1975:
        return '1965-1975'
    elif year < 1985:
        return '1975-1985'
    elif year < 1995:
        return '1985-1995'
    elif year < 2005:
        return '1995-2005'
    elif year < 2015:
        return '2005-2015'
    else:
        return '2015-2020'

In [19]:
def use_surface_classes(use_surface):
    if use_surface < 50:
        return '-50 m2'
    elif use_surface < 75:
        return '50-75 m2'
    elif use_surface < 100:
        return '75-100 m2'
    elif use_surface < 150:
        return '100-150 m2'
    elif use_surface < 250:
        return '150-250 m2'
    else:
        return '250+'

In [20]:
def parcel_surface_classes(parcel_surface):
    if parcel_surface < 50:
        return '-50 m2'
    elif parcel_surface < 100:
        return '50-100 m2'
    elif parcel_surface < 250:
        return '100-250 m2'
    elif parcel_surface < 500:
        return '250-500 m2'
    elif parcel_surface < 1000:
        return '500-1000 m2'
    else:
        return '1000+'

In [13]:
df = df_address.copy()

In [14]:
df['amount'] = df['amount'].apply(amount_classes)
df['build_year'] = df['build_year'].apply(build_year_classes)
df['use_surface'] = df['use_surface'].apply(use_surface_classes)
df['parcel_surface'] = df['parcel_surface'].apply(parcel_surface_classes)

In [18]:
df

,date,amount,build_year,build_type,use_surface,parcel_surface,lon,lat,energy_label,number_of_objects,buurt_code,id
0,31/10/2019,200_000-250_000,1975-1985,Flatwoning (overig),41,3004,4.880518,52.389801,B,15,3631301,0
1,31/10/2019,500_000-750_000,1850-1905,Flatwoning (overig),45,616,4.888572,52.377720,G,12,3630200,1
2,31/10/2019,350_000-400_000,1925-1945,Flatwoning (overig),40,124,4.881288,52.376377,D,8,3630611,2
3,31/10/2019,1_500_000-5_000_000,1050-1850,Flatwoning (overig),196,146,4.886696,52.372057,G,3,3630202,3
4,31/10/2019,1_000_000-1_500_000,1905-1925,Maisonnette,115,85,4.882979,52.368475,F,3,3630203,4
5,31/10/2019,1_500_000-5_000_000,2015-2020,Flatwoning (overig),160,436,4.887275,52.364098,A,6,3630300,5
6,31/10/2019,750_000-1_000_000,1995-2005,Flatwoning (overig),90,100,4.893679,52.359622,B,5,3630705,6
7,31/10/2019,500_000-750_000,1995-2005,Flatwoning (overig),100,1137,4.912382,52.362260,B,38,3630801,7
8,31/10/2019,500_000-750_000,1850-1905,Maisonnette,64,108,4.919689,52.369686,C,2,3630902,8
9,31/10/2019,500_000-750_000,1995-2005,Flatwoning (overig),99,1792,4.938037,52.370260,C,59,3633306,9
10,31/10/2019,400_000-500_000,1985-1995,Flatwoning (overig),85,7719,4.947305,52.377413,B,225,3633303,10
11,31/10/2019,350_000-400_000,2005-2015,Flatwoning (overig),83,1143,4.931085,52.405178,A,33,3637402,11
12,31/10/2019,300_000-350_000,1905-1925,Rijwoning hoek,37,5118,4.927524,52.387234,G,1,3636102,12
13,31/10/2019,350_000-400_000,1965-1975,Flatwoning (overig),95,1429,4.949346,52.396726,G,65,3636801,13
14,31/10/2019,250_000-300_000,1965-1975,Flatwoning (overig),85,3291,4.957850,52.390952,C,96,3636805,14
15,31/10/2019,200_000-250_000,1965-1975,Flatwoning (overig),49,5389,4.946713,52.395638,C,8,3636802,15
16,31/10/2019,250_000-300_000,1965-1975,Flatwoning (overig),79,1048,4.947646,52.402266,E,56,3636912,16
17,31/10/2019,50_000-100_000,2015-2020,Flatwoning (overig),85,157,4.892229,52.401516,A,262,3637105,17
18,31/10/2019,500_000-750_000,2005-2015,Rijwoning tussen,166,126,4.901779,52.408216,A,1,3636503,18
19,31/10/2019,250_000-300_000,1850-1905,Flatwoning (overig),43,84,4.874118,52.383060,D,4,3631403,19
20,31/10/2019,300_000-350_000,1905-1925,Flatwoning (overig),42,95,4.869095,52.381780,E,4,3631404,20
21,31/10/2019,400_000-500_000,1905-1925,Flatwoning (overig),20,89,4.868317,52.381749,G,5,3631404,21
22,31/10/2019,350_000-400_000,1850-1905,Flatwoning (overig),40,78,4.860634,52.360846,C,5,3632100,22
23,31/10/2019,750_000-1_000_000,1905-1925,Flatwoning (overig),118,142,4.858980,52.360434,E,4,3632100,23
24,31/10/2019,350_000-400_000,2005-2015,Flatwoning (overig),72,4565,4.847349,52.376470,A,124,3633802,24
25,31/10/2019,350_000-400_000,1925-1945,Flatwoning (overig),64,142,4.850782,52.376764,G,4,3633802,25
26,31/10/2019,350_000-400_000,1925-1945,Flatwoning (overig),58,1423,4.852086,52.376985,D,4,3633802,26
27,31/10/2019,300_000-350_000,1925-1945,Flatwoning (overig),64,194,4.848599,52.383585,D,8,3633702,27
28,31/10/2019,500_000-750_000,1905-1925,Flatwoning (overig),49,160,4.859442,52.375859,B,4,3633703,28
29,31/10/2019,300_000-350_000,1925-1945,Flatwoning (overig),45,2212,4.863870,52.372760,D,8,3634000,29
...,...,...,...,...,...,...,...,...,...,...,...,...
4530776,2/1/1995,200_000-250_000,1955-1965,Flatwoning (overig),178,285,6.097628,53.107577,E,3,900001,4530776
4530777,2/1/1995,50_000-100_000,1965-1975,Flatwoning (overig),48,2253,6.427235,53.127352,E,71,16990000,4530777
4530778,2/1/1995,50_000-100_000,1985-1995,2-onder-1-kapwoning,126,268,6.408511,53.134145,C,1,16990010,4530778
4530779,2/1/1995,50_000-100_000,1945-1955,Vrijstaande woning,132,545,6.395826,53.130982,G,1,16990030,4530779
4530780,2/1/1995,50_000-100_000,1925-1945,Vrijstaande woning,180,408,6.456579,53.068034,G,1,16990300,4530780
4530781,2/1/1995,50_000-100_000,1985-1995,2-onder-1-kapwoning,106,224,6.344996,53.126089,B,1,19690500,4530781
4530782,2/1/1995,100_000-150_000,1925-1945,Vrijstaande woning,191,480,6.566004,52.989485,F,1,1060011,4530782
4530783,2/1/1995,200_000-250_000,1985-1995,Vrijstaande woning,188,503,6.576127,53.020947,B,1,1060705,4530783
4530784,2/1/1995,50_000-100_000,1985-1995,2-onder-1-kapwoning,131,217,6.566574,53.020979,C,1,1060602,4530784
4530785,2/1/1995,100_000-150_000,1985-1995,Vrijstaande woning,178,438,6.718864,53.054034,C,1,16800000,4530785
4530786,2/1/1995,100_000-150_000,1985-1995,Vrijstaande woning,153,1570,7.060194,52.862637,B,1,19500900,4530786
4530787,2/1/1995,50_000-100_000,1850-1905,2-onder-1-kapwoning,111,327,6.877963,53.100407,G,1,470003,4530787
4530788,2/1/1995,50_000-100_000,1965-1975,Rijwoning tussen,69,139,6.859012,53.105176,C,1,470005,4530788
4530789,2/1/1995,50_000-100_000,1905-1925,Vrijstaande woning,108,850,6.837809,53.055096,G,1,16801200,4530789
4530790,2/1/1995,50_000-100_000,1850-1905,Flatwoning (overig),35,100,6.573963,53.216589,G,2,140001,4530790
4530791,2/1/1995,150_000-200_000,1985-1995,NaN,158,117,6.574124,53.218291,NaN,1,140002,4530791
4530792,2/1/1995,150_000-200_000,1905-1925,Maisonnette,30,127,6.562445,53.224835,A,5,140005,4530792
4530793,2/1/1995,100_000-150_000,1975-1985,Rijwoning tussen,154,225,6.570960,53.188059,C,1,140606,4530793
4530794,2/1/1995,50_000-100_000,1850-1905,Rijwoning tussen,83,75,6.581082,53.201008,D,1,140604,4530794
4530795,2/1/1995,50_000-100_000,1905-1925,Rijwoning tussen,94,82,6.579448,53.213515,F,1,140101,4530795
4530796,2/1/1995,50_000-100_000,1925-1945,Flatwoning (overig),97,197,6.563156,53.206236,G,3,140103,4530796
4530797,2/1/1995,750_000-1_000_000,1995-2005,NaN,80,1751,6.587624,53.246634,NaN,4,141100,4530797
4530798,2/1/1995,50_000-100_000,1925-1945,2-onder-1-kapwoning,128,130,6.502069,53.212909,G,1,140800,4530798
4530799,2/1/1995,50_000-100_000,1965-1975,Vrijstaande woning,102,292,6.594629,53.300887,D,1,19660000,4530799
4530800,2/1/1995,50_000-100_000,1985-1995,Vrijstaande woning,135,954,6.279209,53.215900,A,1,19690000,4530800
4530801,2/1/1995,50_000-100_000,1955-1965,Vrijstaande woning,152,2500,6.253264,53.201677,B,1,19690001,4530801
4530802,2/1/1995,50_000-100_000,1995-2005,2-onder-1-kapwoning,155,242,6.856641,53.324052,B,1,30000,4530802
4530803,2/1/1995,50_000-100_000,1975-1985,2-onder-1-kapwoning,151,476,6.934623,53.250676,C,1,100944,4530803
4530804,2/1/1995,50_000-100_000,1985-1995,Vrijstaande woning,96,299,6.377216,53.356804,B,1,19661001,4530804
4530805,2/1/1995,50_000-100_000,1925-1945,Vrijstaande woning,110,242,6.636191,53.347510,G,1,240200,4530805